hooter/hooter/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'hooter.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
	url(r'^', include('hooter_app.urls')),
	
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hooter/hooter_app/urls.py
from django.conf.urls import patterns, include, url

from hooter_app import views

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	url(r'^connexion$',views.connexion,name='connexion'),
	url(r'^recuperation_mot_de_passe$',views.recup_pass,name='recuperation_mot_de_passe'),
	url(r'^deconnexion$',views.deconnexion,name='deconnexion'),
	url(r'^recherche$',views.rechercher,name='recherche'),
	url(r'^enregistrement$',views.enregistrement,name='enregistrement'),
	url(r'^#(?P<hashtag>\w+)$',views.afficher_hashtag, name='afficher_hashtag'),
	url(r'^hashtag/(?P<hashtag>\w+)$',views.afficher_hashtag, name='afficher_hashtag_full'),
	url(r'^(?P<pseudo>\w+)/$',views.profile_view, name='profile_view'),
	url(r'^(?P<pseudo>\w+)/settings',views.modif_profil,name='modif_profil'),
	url(r'^enregistrer_profil$',views.enregistrer_profil,name='enregistrer_profil'),
	url(r'^suivre(?P<pseudo>\w+)$',views.suivre,name='suivre'),
	url(r'^envoyer_message$',views.envoyer_message,name='envoyer_message'),	
	url(r'^sedesabonner(?P<pseudo>\w+)$',views.sedesabonner,name='sedesabonner'),
	url(r'^(?P<pseudo>\w+)/password$',views.modif_password,name='modif_password'),
	url(r'^(?P<pseudo>\w+)/abonnes',views.liste_abonnes,name='liste_abonnes'),
	url(r'^(?P<pseudo>\w+)/abonnements',views.liste_abonnements,name='liste_abonnements'),
	url(r'^supprimer(?P<id_message>\w+)$',views.supprimer,name='supprimer'),
	url(r'^retweet(?P<id_message>\w+)$',views.retweet,name='retweet'),
		
)

hooter/hooter_app/models.py
# -*-coding:utf-8 -*
from django.db import models
from django.utils.safestring import SafeUnicode


#representation d'un utilisateur en base
class Utilisateur(models.Model):
	pseudo=models.CharField(max_length=20,unique=True)#son pseudo, unique, cle primaire
	nom=models.CharField(max_length=20)
	mot_passe=models.CharField(max_length=50)
	email=models.CharField(max_length=50,unique=True)
	pays=models.CharField(max_length=50)
	ville=models.CharField(max_length=50)
	date_naiss=models.DateField()
	photo=photo = models.ImageField(upload_to="photos/",blank=True, null=True,default="photos/default.jpeg")
	#lien many-to-many vers utilisateurs pour les abonnements
	abonnements=models.ManyToManyField("Utilisateur",blank=True,related_name="abonnements+")
	#lien many-to-many vers utilisateurs pour les abonnes
	abonnes=models.ManyToManyField("Utilisateur",blank=True,related_name="abonnes+")

	def __unicode__(self):
	        return self.pseudo

#representation d'un tweet
class Message(models.Model):
	contenu=models.CharField(max_length=140)
	date=models.DateTimeField()
	utilisateur=models.ForeignKey(Utilisateur)#l'utilisateur actuel du message
	utilisateur_createur=models.ForeignKey(Utilisateur,related_name="utilisateur_createur+", null=True)#l'utilisateur qui a créé le message en premier
	hashtags=models.ManyToManyField("Hashtag", blank=True)

	def __unicode__(self):
	        return SafeUnicode(self.contenu)[0:15]

#representation d'un hashtag
class Hashtag(models.Model):
	nom=models.CharField(max_length=20)
	messages=models.ManyToManyField(Message, blank=True)

	def __unicode__(self):
	        return self.nom




	

	

hooter/hooter_app/forms.py
# -*-coding:utf-8 -*

from django import forms
from hooter_app.models import Utilisateur
from django.forms.extras.widgets import SelectDateWidget

#formulaire de connexion d'un utilisateur
class ConnexionForm(forms.ModelForm):
	
	email = forms.EmailField(required=True,widget=forms.EmailInput(attrs={'placeholder': 'Email','class' : 'form-control'}),label='')
	mot_passe = forms.CharField(required=True,widget=forms.PasswordInput(attrs={'placeholder': 'Mot de passe','class' : 'form-control'}),label='')
	class Meta:
		model = Utilisateur
		fields = ['email','mot_passe']
	def validate_unique(self):
		pass
		
#formulaire de recuperation de mot de passe
class RecupPassForm(forms.ModelForm):
	
	email = forms.EmailField(required=True,widget=forms.EmailInput(attrs={'placeholder': 'Email','class' : 'form-control'}),label='Adresse Email')
	class Meta:
		model = Utilisateur
		fields = ['email']
	def validate_unique(self):
		pass
		
#formulaire d'enregistrement d'utilisateur
class EnregistrementForm(forms.ModelForm):
	email = forms.EmailField(required=True,widget=forms.EmailInput(attrs={'placeholder': 'Email','class' : 'form-control'}),label='Email')
	mot_passe = forms.CharField(required=True,widget=forms.PasswordInput(attrs={'placeholder': 'Mot de passe','class' : 'form-control'}),label='Mot de passe')
	pseudo = forms.CharField(required=True,widget=forms.TextInput(attrs={'placeholder': 'Pseudo','class' : 'form-control'}),label='Pseudo')
	pays = forms.CharField(required=True,widget=forms.TextInput(attrs={'placeholder': 'Pays','class' : 'form-control'}),label='Pays')
	ville = forms.CharField(required=True,widget=forms.TextInput(attrs={'placeholder': 'Ville','class' : 'form-control'}),label='Ville')
	date_naiss = forms.DateField(required=True,widget=forms.DateInput(attrs={'placeholder': 'Date','class' : 'form-control'}),label='Date de naissance',input_formats=['%d/%m/%Y','%d-%m-%Y'])

	class Meta:
		model = Utilisateur
		fields = ['email','mot_passe','pseudo','pays','ville','date_naiss']
	

#formulaire de modification de profil d'utilisateur
class Modif_profilForm(forms.ModelForm):
	email = forms.EmailField(required=True,widget=forms.EmailInput(attrs={'placeholder': 'Email','class' : 'form-control'}),label='Email')
	nom = forms.CharField(required=True,widget=forms.TextInput(attrs={'placeholder': 'Nom','class' : 'form-control'}),label='Nom')
	pays = forms.CharField(required=True,widget=forms.TextInput(attrs={'placeholder': 'Pays','class' : 'form-control'}),label='Pays')
	ville = forms.CharField(required=True,widget=forms.TextInput(attrs={'placeholder': 'Ville','class' : 'form-control'}),label='Ville')
	date_naiss = forms.DateField(required=True,widget=forms.DateInput(attrs={'placeholder': 'Date','class' : 'form-control'}),label='Date de naissance')
	photo  = forms.ImageField(required=False)
	class Meta:
		model = Utilisateur
		fields = ['nom','email','pays','ville','date_naiss','photo']

hooter/hooter_app/views.py
# -*-coding:utf-8 -*
from django.shortcuts import redirect
from hooter_app.forms import ConnexionForm,EnregistrementForm,RecupPassForm, Modif_profilForm
from hooter_app.models import Utilisateur
from django.shortcuts import render,get_object_or_404
from django.views.decorators.csrf import csrf_protect
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse
from hooter_app.models import Utilisateur, Message, Hashtag
from django.conf import settings
from django.core.mail import send_mail
import datetime
from django.db.models import Q


###methode pour afficher l'index###
def index(request):
	if not 'pseudo' in request.session	:	
		formulaire = ConnexionForm()
		formEnregistrement = EnregistrementForm()
		contexte = {'formulaire':formulaire,'formEnregistrement':formEnregistrement,}
		return render(request, 'index.html',contexte)
	else:
		#si utilisateur connecte, on recupere les message de sa timeline
		utilisateur=get_object_or_404(Utilisateur, pseudo=request.session['pseudo'])
		abonnement=utilisateur.abonnements.all()
		#recupere ses messages, les messages de ses abonnements et les messages ou il est cite, par date
		message=Message.objects.all().filter(Q(utilisateur=abonnement) | Q(contenu__contains="@"+utilisateur.pseudo)).order_by('date')
		contexte={'utilisateur' : utilisateur, 'abonnement':abonnement, 'message':message}

		
		return render(request, 'index.html',contexte)


def afficher_hashtag(request, hashtag):
	contexte = {}
	try:
		hashtags_correspondants = Hashtag.objects.all().filter(nom__contains=hashtag)

		messages_hashtags=Message.objects.all().filter(hashtags=hashtags_correspondants).order_by('date')
		contexte['resultats_messages'] = messages_hashtags
	except Hashtag.DoesNotExist:
		pass

	
	contexte['recherche'] = hashtag
	return render(request, "affiche_hashtag.html", contexte)
	

@csrf_protect
def envoyer_message(request):
	
	if 'message' in request.POST:
		print request.POST['message']
		message_a_envoyer = Message()
		utilisateur_courant = Utilisateur.objects.get(pseudo=request.session['pseudo'])
		message_a_envoyer.contenu = request.POST['message']
		message_a_envoyer.date = datetime.datetime.now()
		message_a_envoyer.utilisateur = utilisateur_courant
		message_a_envoyer.utilisateur_createur = utilisateur_courant
		
		message_a_envoyer.save()
		
		tampon = request.POST['message']
		#on remplace les ,!;:./?*$'" par des espace (whitespace)
		for char in ',!;:./?*$\'"\r\n\\':
			tampon = tampon.replace(char,' ')
		message_split = tampon.split()
		print 'message splitté : %s'%message_split
		for mot in message_split:
			#test pour supprimer tout mot avant le # non voulu (on veut le hashtag ici uniquement)
			if '#' in mot:
				if mot.replace('#','') != '':
					for char in mot:
						if char == '#':
							break
						else:
							mot = mot.replace(char,'',1)
					
					print 'hashtag : %s'%mot
					
					try:
						#on essaie de recuperer le hashtag dans la base de données pour voir s'il existe deja
						hashtag_a_enregistrer = Hashtag.objects.get(nom=mot)
					except Hashtag.DoesNotExist:
						#s'il existe pas, alors on le cree
						hashtag_a_enregistrer = Hashtag()
						hashtag_a_enregistrer.nom = mot
						hashtag_a_enregistrer.save()
					#on ajoute au hashtag le lien vers le message
					hashtag_a_enregistrer.messages.add(message_a_envoyer)
					hashtag_a_enregistrer.save()
					
					#pour chaque hashtag on l'ajoute dans le message courant, et on enregistre la modification des hashtags dans le message
					message_a_envoyer.hashtags.add(hashtag_a_enregistrer)
					message_a_envoyer.save()
	
	return redirect('index')		
		
def recup_pass(request):
	if 'email' in request.POST:
		recup = RecupPassForm(request.POST)
		if recup.is_valid():
			try:
				utilisateur = Utilisateur.objects.get(email=recup.cleaned_data['email'])
				sujet = "Recuperation mot de passe - Hooter"
				corps = "Vous aviez perdu votre mot de passe. Le voici : %s"%utilisateur.mot_passe
				emetteur = "webmaster@hooter.com"
				destinataires = [utilisateur.email,]
				
				send_mail(sujet,corps,emetteur,destinataires)
				return render(request,'recuperation.html',{'formulaire_recuperation':recup,'succes':'Mot de passe envoyé avec succès!'})
			except Utilisateur.DoesNotExist:
				return render(request,'recuperation.html',{'formulaire_recuperation':recup,'errors':'Adresse mail non reconnue.'})
		else:
			
			render(request,'recuperation.html',{'formulaire_recuperation':recup,})
	
	else:
		recup = RecupPassForm()
	
	return render(request,'recuperation.html',{'formulaire_recuperation':recup,})

def deconnexion(request):
	request.session.flush()
	formulaire = ConnexionForm()
	formEnregistrement = EnregistrementForm()
	contexte = {'formulaire':formulaire,'formEnregistrement':formEnregistrement,}
	return render(request, 'index.html',contexte)

@csrf_protect
def rechercher(request):
	if 'champ_recherche' in request.POST:
		##recherche des differents utilisateurs
		nom_utilisateur = request.POST['champ_recherche']
		utilisateurs_correspondants=[]
		contexte = {'recherche':request.POST['champ_recherche'],}
		try:
			utilisateurs_correspondants = Utilisateur.objects.all().filter(pseudo=nom_utilisateur)
		except Utilisateur.DoesNotExist:
			pass
		contexte['resultats_utilisateurs'] = utilisateurs_correspondants
		
		##recherche des hashtags
		hashtags_correspondants = []
		messages_hashtags = []
		try:
			hashtag_recherche = request.POST['champ_recherche']
			for char in hashtag_recherche:
					if char == '#':
						break
					else:
						hashtag_recherche = hashtag_recherche.replace(char,'',1)
			#si le hashtag est maintenant vide, alors c'est qu'on recherchait pas de hashtag ! On leve donc une exception
			if hashtag_recherche=="":
				raise Hashtag.DoesNotExist()
			
			hashtags_correspondants = Hashtag.objects.all().filter(nom__contains=hashtag_recherche)
			
			messages_hashtags=Message.objects.all().filter(hashtags=hashtags_correspondants).order_by('date')
		except Hashtag.DoesNotExist:
			pass
		contexte['hashtags_correspondants']=hashtags_correspondants
		contexte['resultats_hashtags'] = messages_hashtags
		
		##recherche dans les messages
		messages_correspondants=[]
		try:
			messages_correspondants = Message.objects.all().filter(contenu__contains = request.POST['champ_recherche'])
		except Message.DoesNotExist:
			pass
			
		contexte['resultats_messages'] = messages_correspondants
		
	else:
		return redirect('index')

	return render(request,'recherche.html',contexte)


@csrf_protect
def connexion(request):
	if 'email' in request.POST:
		formulaire=ConnexionForm(request.POST)
		contexte = {'formulaire':formulaire,'formEnregistrement':EnregistrementForm()}
		if formulaire.is_valid():
			try:
				utilisateur = Utilisateur.objects.get(email=formulaire.cleaned_data['email'],mot_passe=formulaire.cleaned_data['mot_passe'])
				
				request.session['pseudo']=utilisateur.pseudo
				return redirect('index')
			except Utilisateur.DoesNotExist:
				contexte['errors']='Utilisateur inconnu'
				return render(request, 'index.html',contexte)
		else:
			if 'email' in formulaire.errors:
				contexte['errors']="Adresse email incorrecte"
			if 'mot_passe' in formulaire.errors:
				try:
					contexte['errors']=contexte['errors']+', mot de passe vide'
				except KeyError:
					contexte['errors'] = "Mot de passe vide"
			return render(request, 'index.html',contexte)
	else:
		return redirect('index')


@csrf_protect		
def enregistrement(request):
	
	if 'email' in request.POST:
		enregistrement = EnregistrementForm(request.POST)#on remplit le formulaire
		
		if enregistrement.is_valid():
			nouvel_utilisateur = Utilisateur()
			nouvel_utilisateur.pseudo = enregistrement.cleaned_data['pseudo']
			nouvel_utilisateur.nom = enregistrement.cleaned_data['pseudo']
			nouvel_utilisateur.email = enregistrement.cleaned_data['email']
			nouvel_utilisateur.mot_passe = enregistrement.cleaned_data['mot_passe']
			nouvel_utilisateur.ville = enregistrement.cleaned_data['ville']
			nouvel_utilisateur.pays = enregistrement.cleaned_data['pays']
			nouvel_utilisateur.date_naiss = enregistrement.cleaned_data['date_naiss']

			nouvel_utilisateur.save()
			
			nouvel_utilisateur.abonnements.add(nouvel_utilisateur)
			nouvel_utilisateur.save()
			
			return render(request,'index.html',{'formEnregistrement':EnregistrementForm(),'formulaire':ConnexionForm(),'succes':'Enregistrement réussi ! Connectez-vous.',})
		else:
			return render(request, 'index.html',{'formEnregistrement':enregistrement,'formulaire':ConnexionForm()})
			
		 
	return HttpResponse("Register!")


def profile_view(request, pseudo):
	if 'pseudo' in request.session:
		infos=get_object_or_404(Utilisateur, pseudo=pseudo)
		utilisateur_co=get_object_or_404(Utilisateur, pseudo=request.session['pseudo'])
		
		contexte={'infos' : infos, 'utilisateur_co':utilisateur_co}
		
		return render(request, 'profile_view.html',contexte)
	else:
		return redirect('index')

@csrf_protect
def modif_profil(request, pseudo):
	if 'pseudo' in request.session and pseudo==request.session['pseudo']:

		utilisateur=get_object_or_404(Utilisateur, pseudo=pseudo)
		formulaire=Modif_profilForm(instance=utilisateur)
		
		contexte={'utilisateur' : utilisateur, 'form':formulaire}

		return render(request, 'modif_profil.html',contexte)
	
	else:
		return redirect('index')
		
		
		

		
@csrf_protect
def enregistrer_profil(request):

	utilisateur=get_object_or_404(Utilisateur, pseudo=request.session['pseudo'])
	formulaire=Modif_profilForm(request.POST,request.FILES, instance=utilisateur)
		
	contexte={'utilisateur' : utilisateur, 'form':formulaire}

	if 'POST' in request.method:
		if formulaire.is_valid():
			formulaire.save()
			
			return redirect('profile_view',request.session['pseudo'])
		else:
			return render(request, 'modif_profil.html', contexte)
	else:
		return redirect(request.session['pseudo'],'/settings')
		

@csrf_protect
def modif_password(request, pseudo):

hooter/hooter_app/templates/index.html
{% extends '_base.html' %}

{% block titre %} Accueil {% endblock %}



{% block autre %}

	{%if request.session.pseudo%}
		<div class="page-header">
			<img src="{{ MEDIA_URL }}{{ utilisateur.photo }}" height="90px" width="90px"/>	
			<h1>{{ utilisateur.nom }} </h1>
			<h2><small>@{{ utilisateur.pseudo }}</small></h2>
		</div>

	  <div class="btn-group">
		<a href='{% url 'profile_view' request.session.pseudo %}'class="btn btn-large btn-default">tweets <br/>{{utilisateur.message_set.count}}</a>
		<a href='{% url 'liste_abonnements' request.session.pseudo %}'class="btn btn-large btn-default">abonnements <br/>{{utilisateur.abonnements.count|add:"-1"}}</a>
		<a href='{% url 'liste_abonnes' request.session.pseudo %}'class="btn btn-large btn-default">abonnés <br/>{{utilisateur.abonnes.count}}</a>

   	</div>
		<form method="post" action="{%url 'envoyer_message'%}" role="form">
			<div class="row">
				<div class="col-lg-6">
					<div class="input-group">
						{% csrf_token %}
						<textarea placeholder="Racontez votre vie!" id="textarea-tweet" style="width:260px;resize:none;" name="message" maxlength="140" class="form-control tweet-textarea" rows="5"></textarea>
							<input type="submit" class="btn btn-primary btn-float-right" value="Envoyer"/>
					</div><!-- /input-group -->
				</div><!-- /.col-lg-6 -->
			</div><!-- /.row -->
		</form>  

    
		
	{% endif %}
	

{% endblock %}



{% block contenu %}
{% load poll_extras %}
		{%if not request.session.pseudo%}
					
			<div class="register">
				{%if succes%}<div class="alert alert-success">{{succes}}</div>{%endif%}
				<div class="alert alert-info">S'enregistrer</div>
			<form  class="form-horizontal" role="form" method="post" action={% url 'enregistrement' %}>
			
				 {% for field in formEnregistrement %}
					<div class="form-group">
					
						{{ field.label_tag }}
						{% for error in field.errors %}
							<span style="color:red">{{error}}</span>
						{%endfor%}
						{{ field }}
					</div>
				{% endfor %}
				{% csrf_token %}<br/>
				<input type="submit" class="btn btn-primary" value="Enregistrement">
			</form>
			</div>

		{%endif%}
		
		
		{%if request.session.pseudo%}
		
			<ul class="list-group">
			  <li class="list-group-item"><h2>tweets</h2></li>
		
				
				
			{% for mess in message reversed  %}
			

			 <li class="list-group-item">
			 
			{%ifequal  mess.utilisateur_createur mess.utilisateur %}
			
			 <div class="media">
				  <a class="pull-left" href="{% url 'profile_view' mess.utilisateur.pseudo %}">
				    <img class="media-object" src="{{ MEDIA_URL }}{{mess.utilisateur.photo }}" height="60px" width="60px" alt="...">
				  </a>
	 		 <div class="media-body">
	 		 <h3 class="media-heading">{{mess.utilisateur.nom }} <small>@{{mess.utilisateur.pseudo }} {{mess.date }} </small></h3>
			    {{mess.contenu|make_url_to_profile_and_hashtag|safe }}
			  </div>
			  
			  {% endifequal %}
			  
			  
			  {%ifnotequal  mess.utilisateur_createur mess.utilisateur %}
				Retweeté par  <a href="{% url 'profile_view' mess.utilisateur.pseudo %}">@{{mess.utilisateur.pseudo }}</a>
			 <div class="media">
				  <a class="pull-left" href="{% url 'profile_view' mess.utilisateur_createur.pseudo %}">
				    <img class="media-object" src="{{ MEDIA_URL }}{{mess.utilisateur_createur.photo }}" height="60px" width="60px" alt="...">
				  </a>
	 		 <div class="media-body">
	 		 <h3 class="media-heading">{{mess.utilisateur_createur.nom }} <small>@{{mess.utilisateur_createur.pseudo }} {{mess.date }} </small></h3>
			     {{mess.contenu|make_url_to_profile_and_hashtag|safe }}
			  </div>
			  
			  {% endifnotequal %}
			  
			  {%ifequal mess.utilisateur.pseudo request.session.pseudo %} <a href="{% url 'supprimer' mess.id %}"><span class="glyphicon glyphicon-trash"></span>Supprimer  </a>
</a>{%endifequal%}
			  
			  {%ifnotequal mess.utilisateur.pseudo request.session.pseudo %}<a onclick="repondre('{{mess.utilisateur}}')"> <span class="glyphicon glyphicon-share-alt"></span>Répondre</a>{%endifnotequal%}
			  {%ifnotequal mess.utilisateur.pseudo request.session.pseudo %} <a href="{% url 'retweet' mess.id %}"><span class="glyphicon glyphicon-retweet"></span>Retweet  </a>
</a>{%endifnotequal%}

			</div>
			
				
			</li>
		
			<script type="text/javascript">
			function repondre(utilisateur){
				$('#textarea-tweet').text("@"+utilisateur+" ");
				$('#textarea-tweet').focus();
				}
			</script>
		
			
			{%endfor %}
			
					</li>	
	
			</ul>


		
		
		
		{%endif%}
{% endblock %}

hooter/hooter_app/templates/profile_view.html
{% extends '_base.html' %}
{% block titre %}  Profil {{ infos.pseudo }}{% endblock %}
{% block autre %}


<div class="page-header">
	<img src="{{ MEDIA_URL }}{{ infos.photo }}" height="90px" width="90px"/>	
	<h1>{{ infos.nom }} </h1>
	<h2><small>@{{ infos.pseudo }}</small></h2>
</div>
	 
	{{ infos.date_naiss }}
	{{ infos.ville }}
	{{ infos.pays}}

	<br/>
	<br/>
		
	<div class="btn-group">
		<a href='{% url 'profile_view' request.session.pseudo %}'class="btn btn-large btn-default">tweets <br/>{{infos.message_set.count}}</a>
		<a href='{% url 'liste_abonnements' request.session.pseudo %}'class="btn btn-large btn-default">abonnements <br/>{{infos.abonnements.count|add:"-1"}}</a>
		<a href='{% url 'liste_abonnes' request.session.pseudo %}'class="btn btn-large btn-default">abonnés <br/>{{infos.abonnes.count}}</a>

   	</div>
    
	<p>
	{% ifequal request.session.pseudo infos.pseudo %}
		<form action="{% url 'modif_profil' infos.pseudo %}" method="POST">
	 		<button type="submit"  value="modif_profil"class="btn btn-primary btn-sm">Editer le profil</button>
		{% csrf_token%} 	</form>
	{% endifequal %}
	

	
	{%ifnotequal  request.session.pseudo infos.pseudo %}
		{%if infos in utilisateur_co.abonnements.all %}
			<form action="{% url 'sedesabonner' infos.pseudo %}" method="POST">
		 		<button type="submit"  value="sedesabonner" class="btn btn-default btn-lg">Se désabonner</button>
			{% csrf_token%} 	</form>
		{% else %}
			<form action="{% url 'suivre' infos.pseudo %}" method="POST">
		 		<button type="submit"  value="suivre" class="btn btn-default btn-lg">Suivre</button>
			{% csrf_token%} 	</form>
	 	{% endif%}
	{% endifnotequal %}
	
  </p>
{% endblock %}


{% block contenu %}
{% load poll_extras %}

<ul class="list-group">
  <li class="list-group-item"><h2>tweets</h2></li>

	{% for message in infos.message_set.all reversed  %}
		
		 <li class="list-group-item">
		 
		  {%ifequal  message.utilisateur_createur.pseudo request.session.pseudo %}
		 
			 <div class="media">
				  <a class="pull-left" href="{% url 'profile_view' message.utilisateur.pseudo %}">
				    <img class="media-object" src="{{ MEDIA_URL }}{{message.utilisateur.photo }}" height="60px" width="60px" alt="...">
				  </a>
	 		 <div class="media-body">
	 		 

	 		
	 		 <h3 class="media-heading">{{message.utilisateur.nom }} <small>@{{message.utilisateur.pseudo }} {{message.date }} </small></h3>
			    
			     {{message.contenu|make_url_to_profile_and_hashtag|safe }}
			  </div>
		  
			   	 {%ifequal  request.session.pseudo message.utilisateur.pseudo %}
			 		 <a href="{% url 'supprimer' message.id %}"><span class="glyphicon glyphicon-trash"></span>Supprimer  </a>
			 	 {% endifequal %}
		  
		  {% endifequal %}
		  
		  
		  {%ifnotequal  message.utilisateur_createur.pseudo message.utilisateur.pseudo %}
		 		Retweeté par  <a href="{% url 'profile_view' message.utilisateur.pseudo %}">@{{message.utilisateur.pseudo }}</a>
			 <div class="media">
				  <a class="pull-left" href="{% url 'profile_view' message.utilisateur_createur.pseudo %}">
				    <img class="media-object" src="{{ MEDIA_URL }}{{message.utilisateur_createur.photo }}" height="60px" width="60px" alt="...">
				  </a>
	 		 <div class="media-body">
	 		 <h3 class="media-heading">{{message.utilisateur_createur.nom }} <small>@{{message.utilisateur_createur.pseudo }} {{message.date }} </small></h3>
			     {{message.contenu|make_url_to_profile_and_hashtag|safe }}
			  </div>
		  {% endifnotequal %}
		<!--  
		  {%ifequal  message.utilisateur_createur.pseudo message.utilisateur.pseudo %}
		 	
			 <div class="media">
				  <a class="pull-left" href="{% url 'profile_view' message.utilisateur.pseudo %}">
				    <img class="media-object" src="{{ MEDIA_URL }}{{message.utilisateur.photo }}" height="60px" width="60px" alt="...">
				  </a>
	 		 <div class="media-body">
	 		 <h3 class="media-heading">{{message.utilisateur.nom }} <small>@{{message.utilisateur.pseudo }} {{message.date }} </small></h3>
			    {{message.contenu|make_url_to_profile_and_hashtag|safe }}
			  </div>
		  
		  {% endifequal %}
		  -->
		  
		
		</div>
			
		</li>
		
		
		
			
	{%endfor %}
	
</ul>

{% endblock %}